### PR TITLE
Starting to prepare version 3.0.0

### PR DESCRIPTION
**Pull request by gmetais**
## Main changes:
- Updated Phantomas to v2.8.0 (with Chrome v114)
- Updated various dependencies

## Breaking changes:
- Requires Node version >= 16
- Removed the waitForResponse option (was deprecated)

### CODE REVIEW

**Comment by Jieiku** [comment]
Exciting.

I looked at each of the commit labels to see what all was changed since then.

I seen a fork for a component was used here, but no idea of the fork is still necessary?

https://github.com/YellowLabTools/YellowLabTools/pull/386/commits/05c883fa3e38e79dcb0816db3f0ec10e08b6ed06

**Comment by Jieiku** [comment]
I am happy to test any release candidates in my Proxmox LXC install, just flag me if you need any testers eventually.

**Comment by gmetais** [comment]
Hi @Jieiku, hi @ousamabenyounes,

I'm betatesting a new YLT version on http://yellowlab.tools:8282/.

It updates 2 rules (Image Optimization & Oversized images) and introduces 3 new rules (Old image formats, Excessive image density (mobile only) & Incorrect sizes paramter).

image

If you have some time to test, let me know your thoughts!

**Comment by Jieiku** [comment]
I noticed some improvements here, looks pretty nice!

- The totalWeight found the site.webmanifest file as well as the favicon files. (love this)
- It found that a couple of my favicons could be further optimized, and I had even used oxipng before, so this is exciting, read the notes and plan to optimize those farther. (love this)

check?
- the currently live yellowlab.tools shows no improvement for my site with Gzip/Brotli but the new version shows I can gain ~492 bytes. Is this because of a newer version of Brotli or Gzip? (https://abridge.netlify.app/)
- I noticed requests number is gone now, I liked being able to see that stat.
- Complex selectors is reporting wrong. (I fixed this on my private instance)

The way I fixed complex selectors reporting on my private instance: https://github.com/YellowLabTools/YellowLabTools/issues/369#issuecomment-1581503946

I had to edit this line to be equal to 6 in order to catch selectors of 4 or more: https://github.com/macbre/analyze-css/blob/f854b44a53d5090c80021c9ec451267f60588687/rules/complex.js#L3

images:

**Comment by Jieiku** [comment]
Total JS execution time seems to be significantly higher on your test site, not sure if this is because of resource limits because its currently in test mode? or if there was something that changed significantly, going to test a few more sites and see if they all report like that.

**Comment by gmetais** [comment]
Thanks a lot for your feedbacks! Alright, I will bring back the Requests rule. I was seeing it as a duplicate of Total Weight, but it has at least one fan :)

Thank you for the analyse-css issue and the JS execution, I will take a look in the next weeks.

I think you can serve the manifest always compressed, but it is safer if you read and respect the `Accept-Encoding` header.

**Comment by Jieiku** [comment]
In the image optimization you mention ImageOptim. I am now realizing these optimization are based on lossy compression, which is actually not a bad idea if you cannot see the difference... I was able to hit the size it was recommending for the reduction by using pngquant followed with oxipng:

```bash
pngquant --skip-if-larger --strip --quality=80-94 --speed 1 *.png
oxipng -o max --strip all -a -Z *-fs8.png
```

You might mention these software in the recommendation note.

**Comment by gmetais** [comment]
Yes, I've changed the tooling behind PNG compression. My reason is because I often see the PNG format used for photographies. The current implementation that just compresses PNG in "lossless" mode won't tell anything about that, even when the picture is ridiculously enormous.

The new implementation doesn't use pngquant or oxipng, it simply compresses lossly with a simple image processing tool called sharp, but with a quality of 90/100. Even if it's quite a high quality, I found out that it was making photography PNGs much smaller than with my old pngquant implementation.

**Comment by Jieiku** [comment]
Thanks!  I am going to experiment a bit and see what settings I need to use in order for the new YellowLabTools to not flag the images. I am going to test several images, should be able to find the sweet spot for lossy that is just below your 90/100 threshold in that tool. (I think I am probably already pretty close)

**Comment by Jieiku** [comment]
For images below the fold, it gets recommended using a javascript library (which I try to avoid when possible).

I wonder if these should count against the score if loading="lazy" is in the img tag, eg:

https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#strategies

```html
<img src="over9000-400.avif" width="400" height="300" loading="lazy">
```

**Comment by Jieiku** [comment]
More info on the Total JS execution time.

It appears to be going by the time that it finished loading, but without taking into account when it started loading.

Yellow Lab Tools even says to view the performance tab in google chrome dev tools which I did.

It is reporting like 900ms because thats when it finished loading, BUT it did not even start loading the javascript until 880ms.

the graph in chrome dev tools looks like this:

**Comment by gmetais** [comment]
> I wonder if these should count against the score if loading="lazy" is in the img tag (I wouldn't think so), eg:

I've deployed a temporary fix for native lazyloading on http://yellowlab.tools:8282. If validated, I'll submit a pull request to Phantomas.

**Comment by gmetais** [comment]
Regarding CPU execution, Phantomas instruments Puppeteer with some custom JS code to be able to properly measure what's happening on the page. So it looks like some of the CPU time reported is falsely attributed to the page. This is going to be hard to fix. There is already an issue filed here: https://github.com/YellowLabTools/YellowLabTools/issues/371

The new image analysis metrics might have increased this JS execution, I'll have to take a look closer :(

**Comment by Jieiku** [comment]
> > I wonder if these should count against the score if loading="lazy" is in the img tag (I wouldn't think so), eg:
> 
> I've deployed a temporary fix for native lazyloading on http://yellowlab.tools:8282. If validated, I'll submit a pull request to Phantomas.

I tested this, I made a page with a bunch of images, and all but one of them I set loading="lazy", the new fix shows correctly that there was only one image below the fold on the page.

**Comment by Jieiku** [comment]
> Regarding CPU execution, Phantomas instruments Puppeteer with some custom JS code to be able to properly measure what's happening on the page. So it looks like some of the CPU time reported is falsely attributed to the page. This is going to be hard to fix. There is already an issue filed here: #371
> 
> The new image analysis metrics might have increased this JS execution, I'll have to take a look closer :(

I really hope you can fix it, until it can be fixed that metric should be adjusted to like 1500ms instead of 500ms before it counts against your score until it can be fixed.

**Comment by Jieiku** [comment]
oooo an easter egg, I just spotted the requests number is back :)

**Comment by Jieiku** [comment]
I noticed that the Total JS execution time now reports correctly :)
Was it difficult to fix?

The only issue I am seeing now is the complex selectors count:

**Comment by gmetais** [comment]
Yes, that's a good news :) 

I didn't change anything in the code. Actually I just moved the beta from a direct install to AWS Lambda. I still need to fix an issue with screenshots.

The fix for complex selectors is in progress here: https://github.com/macbre/analyze-css/pull/964.

**Comment by macbre** [comment]
The above PR has been merged and released as a part of https://github.com/macbre/analyze-css/releases/tag/v2.2.0

**Comment by gmetais** [comment]
Thanks a lot @macbre and @rdamlenc!
I'll watch carefully when analyze-css gets updated in phantomas :)

**Comment by Jieiku** [comment]
I inquired into analyze-css, if there are any tasks that need done I will see if I can help.

https://github.com/macbre/phantomas/issues/1421

**Pull request merged**
