### PR TITLE
Change default user agent

### PR DESCRIPTION
**Pull request by smeeckaert**
Hi,

I've run into a simple problem with the tool when testing on local projects, basically (and i think i'm not the only one) i've got a different configuration between production and development environment.

For example i don't link the compressed javascript in development but to individual files to increase reactivity when developping. I tried to detect efficiently phantomas in order to simulate a prod environment on my dev machine but the user agent is too "classic".

So here is a proposal to add a "YTL" element in the user agent that could be easily detected by the website.

### CODE REVIEW

**Comment by gmetais** [comment]
Sure, why not! Thanks a lot for your Pull Request!

I'm closing it but don't worry, I'm merging on the develop branch instead of master.

Then I'll try to push to production soon.

**Comment by smeeckaert** [comment]
Oh okay, sorry i didn't pay attention to the branches.

**Comment by gmetais** [comment]
I often make the mistake too.

I think I should change the default branch to "develop", but then GitHub would show an unreleased version of README and files to visitors. I wonder what other projects do to avoid that.

**Comment by gmetais** [comment]
Version 1.8.2 is deployed :)

**Comment by smeeckaert** [comment]
I think a little doc on "how to contribute" could help prevent the mistake, even if it's just 2-3 lines in the project readme.

**Pull request closed without merging**
